# Site settings
title: KJ Grubiak
tagline: I get cheese.

email: kjgrubiak@gmail.com
description: >
  KJ Grubiak is a technology sales professional at Oracle in Austin, TX.
baseurl: ""
url: "https://quesokaje.com"

# Build settings
markdown: kramdown
include: ["_pages"]

# Data Collections
collections:
  experience:
    output: true
    permalink: /:collection/:path
  projects:
    output: true
    permalink: /:collection/:path
