# Site settings
title: Will Cray
tagline: IQ meets EQ.

email: will@willcray.com
description: >
  Will Cray is a M.S. in Computer Science with a focus on AI candidate
  at The University of Texas at Austin (UT), a Freelance Data Scientist, a
  former Intel Autonomous Driving engineer and a graduate of the University of
  Virginia (UVA) with a B.S. as a Computer and Electrical Engineering double major.
baseurl: ""
url: "https://willcray.com"

# Build settings
markdown: kramdown
include: ["_pages"]

# Data Collections
collections:
  experience:
    output: true
    permalink: /:collection/:path
  projects:
    output: true
    permalink: /:collection/:path
