version: '2'

services:
  jekyll:
    image: jekyll/jekyll:pages
    container_name: jekyll-dev
    command: jekyll serve --watch --force_polling --config _config.yml,_config_dev.yml
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
